-- people
insert into "schoolerp".people (oid, people_id, people_type, name_en, name_bn, date_of_birth, email, mobile_no, gender, religion, nationality, blood_group, national_id_no, birth_registration_no, father_name_en, father_name_bn, mother_name_en, mother_name_bn, emergency_contact_person, emergency_contact_no, present_address_json, permanent_address_json, photo_path, photo_url, status, institute_oid) values ('SCHOOL-ERP-People-Oid-00001','P-2022208M0001','Asset Holder','MD KHIRUL ALAM MILON','মোঃ খিরুল আলম মিলন','1980-01-01','moniruzzaman.liton@doer.com.bd','01810176820','Male','Islam','Bangladeshi','B+',null,null,null,null,null,null,null,null,null,null,null,null,'Active','SCHOOL-ERP-Demo-School-001');
insert into "schoolerp".people (oid, people_id, people_type, name_en, name_bn, date_of_birth, email, mobile_no, gender, religion, nationality, blood_group, national_id_no, birth_registration_no, father_name_en, father_name_bn, mother_name_en, mother_name_bn, emergency_contact_person, emergency_contact_no, present_address_json, permanent_address_json, photo_path, photo_url, status, institute_oid) values ('SCHOOL-ERP-People-Oid-00002','P-2022208M0002','Asset Holder','MONIR HOSSAIN PRODHAN','মনির হোসেন প্রধান','1980-01-01','moniruzzaman.liton@doer.com.bd','01810176820','Male','Islam','Bangladeshi','B+',null,null,null,null,null,null,null,null,null,null,null,null,'Active','SCHOOL-ERP-Demo-School-001');
insert into "schoolerp".people (oid, people_id, people_type, name_en, name_bn, date_of_birth, email, mobile_no, gender, religion, nationality, blood_group, national_id_no, birth_registration_no, father_name_en, father_name_bn, mother_name_en, mother_name_bn, emergency_contact_person, emergency_contact_no, present_address_json, permanent_address_json, photo_path, photo_url, status, institute_oid) values ('SCHOOL-ERP-People-Oid-00003','P-2022208M0003','Asset Holder','BORHAN UDDIN SARKER SWAPON','বোরহান উদ্দিন সরকার স্বপন','1980-01-01','moniruzzaman.liton@doer.com.bd','01810176820','Male','Islam','Bangladeshi','B+',null,null,null,null,null,null,null,null,null,null,null,null,'Active','SCHOOL-ERP-Demo-School-001');
insert into "schoolerp".people (oid, people_id, people_type, name_en, name_bn, date_of_birth, email, mobile_no, gender, religion, nationality, blood_group, national_id_no, birth_registration_no, father_name_en, father_name_bn, mother_name_en, mother_name_bn, emergency_contact_person, emergency_contact_no, present_address_json, permanent_address_json, photo_path, photo_url, status, institute_oid) values ('SCHOOL-ERP-People-Oid-00004','P-2022208M0004','Asset Holder','NURUL HOQUE DEWAN','নুরুল হক দেওয়ান','1980-01-01','moniruzzaman.liton@doer.com.bd','01810176820','Male','Islam','Bangladeshi','B+',null,null,null,null,null,null,null,null,null,null,null,null,'Active','SCHOOL-ERP-Demo-School-001');
insert into "schoolerp".people (oid, people_id, people_type, name_en, name_bn, date_of_birth, email, mobile_no, gender, religion, nationality, blood_group, national_id_no, birth_registration_no, father_name_en, father_name_bn, mother_name_en, mother_name_bn, emergency_contact_person, emergency_contact_no, present_address_json, permanent_address_json, photo_path, photo_url, status, institute_oid) values ('SCHOOL-ERP-People-Oid-00005','P-2022208M0005','Asset Holder','DIL MOHAMMED','দিল মোহাম্মাদ','1980-01-01','moniruzzaman.liton@doer.com.bd','01810176820','Male','Islam','Bangladeshi','B+',null,null,null,null,null,null,null,null,null,null,null,null,'Active','SCHOOL-ERP-Demo-School-001');
insert into "schoolerp".people (oid, people_id, people_type, name_en, name_bn, date_of_birth, email, mobile_no, gender, religion, nationality, blood_group, national_id_no, birth_registration_no, father_name_en, father_name_bn, mother_name_en, mother_name_bn, emergency_contact_person, emergency_contact_no, present_address_json, permanent_address_json, photo_path, photo_url, status, institute_oid) values ('SCHOOL-ERP-People-Oid-00006','P-2022208M0006','Asset Holder','DILIP KUMAR DAS','দিলীপ কুমার দাস','1980-01-01','moniruzzaman.liton@doer.com.bd','01810176820','Male','Hindu','Bangladeshi','B+',null,null,null,null,null,null,null,null,null,null,null,null,'Active','SCHOOL-ERP-Demo-School-001');
commit;


